# Generated by Django 2.2.7 on 2019-11-23 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion del objeto')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha de modificacion del objeto')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=1, verbose_name='Estado de la tarea')),
                ('admin', models.ForeignKey(help_text='Usuario admin que creo la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(help_text='Usuario responsable de la tarea', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
            },
        ),
    ]
