# Generated by Django 2.2.7 on 2019-11-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='state',
            field=models.CharField(default='1', max_length=1, verbose_name='Estado de la tarea'),
        ),
    ]
